# -*- coding: utf-8 -*-
"""deeplearning_final_week04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/128Vt1gdM-QmAVkWCbRHvIv6z59gLK3wG
"""

import torch
import torch.nn as nn
import matplotlib.pyplot as plt
from torchvision import datasets, transforms
from torch.utils.data import DataLoader, random_split
from collections import Counter

from google.colab import drive
drive.mount('/content/drive')

data_path = "/content/drive/MyDrive/deeplear final/PlantVillage"

transform = transforms.Compose([
    transforms.Resize((224, 224)),   # делаем одинаковый размер
    transforms.ToTensor(),            # переводим в числа
    transforms.Normalize([0.5,0.5,0.5],
                         [0.5,0.5,0.5])  # нормализация
])

dataset = datasets.ImageFolder(root=data_path, transform=transform)

print("Classes:", dataset.classes)
print("Num classes:", len(dataset.classes))
print("Total images:", len(dataset))

counter = Counter(dataset.targets)
print(counter)

train_size = int(0.8 * len(dataset))
val_size = len(dataset) - train_size

train_data, val_data = random_split(dataset, [train_size, val_size])

train_loader = DataLoader(train_data, batch_size=16, shuffle=True)
val_loader = DataLoader(val_data, batch_size=16, shuffle=False)

images, labels = next(iter(train_loader))

plt.figure(figsize=(10,5))

for i in range(6):
    plt.subplot(2,3,i+1)

    img = images[i].permute(1,2,0)
    img = img * 0.5 + 0.5

    plt.imshow(img)
    plt.title(dataset.classes[labels[i]])
    plt.axis("off")

plt.show()

class BaselineCNN(nn.Module):
    def __init__(self, num_classes):
        super().__init__()

        self.conv = nn.Sequential(
            nn.Conv2d(3, 16, 3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(16, 32, 3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),
        )

        self.fc = nn.Sequential(
            nn.LazyLinear(128),
            nn.ReLU(),
            nn.Linear(128, num_classes)
        )

    def forward(self, x):
        x = self.conv(x)
        x = x.view(x.size(0), -1)
        return self.fc(x)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = BaselineCNN(len(dataset.classes)).to(device)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

def train_one_epoch():
    model.train()
    total_loss = 0

    for x, y in train_loader:
        x, y = x.to(device), y.to(device)

        out = model(x)
        loss = criterion(out, y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    return total_loss / len(train_loader)


def evaluate():
    model.eval()
    correct = 0
    total = 0

    with torch.no_grad():
        for x, y in val_loader:
            x, y = x.to(device), y.to(device)

            out = model(x)
            _, pred = torch.max(out, 1)

            correct += (pred == y).sum().item()
            total += y.size(0)

    return correct / total

import torch
print(torch.cuda.is_available())

import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))



#week3

import torch
import torch.nn as nn
import torch.nn.functional as F
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import numpy as np
import json, time, os
from pathlib import Path
from collections import Counter

from torchvision import datasets, transforms
from torch.utils.data import DataLoader, random_split, WeightedRandomSampler
from torch.optim.lr_scheduler import CosineAnnealingLR
from sklearn.metrics import (
    f1_score, confusion_matrix, classification_report
)
from tqdm.notebook import tqdm

#config
CFG = {
    "data_path":    "/content/drive/MyDrive/deeplear final/PlantVillage",
    "img_size":     128,      # 128 быстрее T4; поменяй на 224 если хочешь max качество
    "batch_size":   64,
    "epochs":       25,
    "lr":           1e-3,
    "weight_decay": 1e-4,
    "dropout":      0.4,
    "val_split":    0.2,
    "seed":         42,
    "num_workers":  2,        # Colab: 2 стабильнее
    "output_dir":   "/content/drive/MyDrive/deeplear final/outputs/week03",
}

Path(CFG["output_dir"]).mkdir(parents=True, exist_ok=True)

torch.manual_seed(CFG["seed"])
np.random.seed(CFG["seed"])

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}  ({torch.cuda.get_device_name(0)})")

#transform
S = CFG["img_size"]

train_transform = transforms.Compose([
    transforms.Resize((S, S)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomVerticalFlip(),
    transforms.RandomRotation(20),
    transforms.ColorJitter(brightness=0.3, contrast=0.3, saturation=0.2),
    transforms.RandomResizedCrop(S, scale=(0.75, 1.0)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225]),
])

val_transform = transforms.Compose([
    transforms.Resize((S, S)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225]),
])

full_dataset = datasets.ImageFolder(root=CFG["data_path"])
class_names  = full_dataset.classes
num_classes  = len(class_names)

print(f"Classes: {num_classes}")
print(f"Total images: {len(full_dataset)}")
print(f"Class distribution: {dict(Counter(full_dataset.targets))}")

# Разбиваем индексы, применяем разные transforms
n_val   = int(len(full_dataset) * CFG["val_split"])
n_train = len(full_dataset) - n_val

train_idx, val_idx = torch.utils.data.random_split(
    range(len(full_dataset)), [n_train, n_val],
    generator=torch.Generator().manual_seed(CFG["seed"])
)

class TransformSubset(torch.utils.data.Dataset):
    def __init__(self, dataset, indices, transform):
        self.dataset   = dataset
        self.indices   = indices
        self.transform = transform
    def __len__(self):
        return len(self.indices)
    def __getitem__(self, i):
        img, label = self.dataset.imgs[self.indices[i]]
        from PIL import Image
        img = Image.open(img).convert("RGB")
        return self.transform(img), label

train_ds = TransformSubset(full_dataset, train_idx.indices, train_transform)
val_ds   = TransformSubset(full_dataset, val_idx.indices,   val_transform)

#weight sampler
train_labels = [full_dataset.targets[i] for i in train_idx.indices]
class_counts = np.bincount(train_labels)
sample_weights = 1.0 / class_counts[train_labels]
sampler = WeightedRandomSampler(sample_weights, len(sample_weights))

train_loader = DataLoader(train_ds, batch_size=CFG["batch_size"],
                          sampler=sampler, num_workers=CFG["num_workers"],
                          pin_memory=True)
val_loader   = DataLoader(val_ds, batch_size=CFG["batch_size"],
                          shuffle=False, num_workers=CFG["num_workers"],
                          pin_memory=True)

print(f"Train batches: {len(train_loader)}  |  Val batches: {len(val_loader)}")

#model
class ConvBlock(nn.Module):
    """Conv3×3 → BN → ReLU → Conv3×3 → BN → ReLU → MaxPool  (+Dropout2d)"""
    def __init__(self, in_ch, out_ch, dropout=0.0):
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(in_ch,  out_ch, 3, padding=1, bias=False),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_ch, out_ch, 3, padding=1, bias=False),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True),
        )
        self.drop = nn.Dropout2d(dropout) if dropout > 0 else nn.Identity()
        self.pool = nn.MaxPool2d(2, 2)

    def forward(self, x):
        return self.pool(self.drop(self.block(x)))

class PlantCNN(nn.Module):
    def __init__(self, num_classes, dropout=0.4):
        super().__init__()
        d = dropout
        self.features = nn.Sequential(
            ConvBlock(3,   32,  dropout=0.0),
            ConvBlock(32,  64,  dropout=d * 0.5),
            ConvBlock(64,  128, dropout=d * 0.5),
            ConvBlock(128, 256, dropout=d),
        )
        self.gap  = nn.AdaptiveAvgPool2d(1)
        self.head = nn.Sequential(
            nn.Flatten(),
            nn.Linear(256, 512),
            nn.ReLU(inplace=True),
            nn.Dropout(dropout),
            nn.Linear(512, num_classes),
        )
        self._init_weights()

    def _init_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, nonlinearity="relu")
            elif isinstance(m, nn.BatchNorm2d):
                nn.init.ones_(m.weight); nn.init.zeros_(m.bias)
            elif isinstance(m, nn.Linear):
                nn.init.xavier_uniform_(m.weight); nn.init.zeros_(m.bias)

    def forward(self, x):
        return self.head(self.gap(self.features(x)))

model = PlantCNN(num_classes, dropout=CFG["dropout"]).to(device)

n_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"\nModel: PlantCNN  |  params: {n_params:,}")

#loss
criterion = nn.CrossEntropyLoss(label_smoothing=0.1)

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=CFG["lr"],
    weight_decay=CFG["weight_decay"]
)

scheduler = CosineAnnealingLR(optimizer, T_max=CFG["epochs"], eta_min=1e-6)

def train_one_epoch():
    model.train()
    total_loss, correct, total = 0, 0, 0

    for x, y in tqdm(train_loader, desc="  train", leave=False):
        x, y = x.to(device), y.to(device)
        optimizer.zero_grad(set_to_none=True)
        out  = model(x)
        loss = criterion(out, y)
        loss.backward()
        nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()

        total_loss += loss.item()
        correct    += (out.argmax(1) == y).sum().item()
        total      += y.size(0)

    return total_loss / len(train_loader), correct / total

@torch.no_grad()
def evaluate():
    model.eval()
    total_loss, correct, total = 0, 0, 0
    all_preds, all_labels = [], []

    for x, y in tqdm(val_loader, desc="  val  ", leave=False):
        x, y = x.to(device), y.to(device)
        out  = model(x)
        loss = criterion(out, y)

        preds = out.argmax(1)
        total_loss += loss.item()
        correct    += (preds == y).sum().item()
        total      += y.size(0)
        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(y.cpu().numpy())

    acc = correct / total
    f1  = f1_score(all_labels, all_preds, average="weighted", zero_division=0)
    return total_loss / len(val_loader), acc, f1, all_preds, all_labels

history = {k: [] for k in
    ["train_loss","val_loss","train_acc","val_acc","val_f1","lr"]}

best_val_acc = 0.0
best_preds, best_labels = [], []
ckpt_path = Path(CFG["output_dir"]) / "best_model.pt"

print(f"\n{'─'*55}")
print(f"  Epoch   Tr-Loss   Val-Loss   Val-Acc   Val-F1   LR")
print(f"{'─'*55}")

t0 = time.time()

for epoch in range(1, CFG["epochs"] + 1):
    tr_loss, tr_acc = train_one_epoch()
    vl_loss, vl_acc, vl_f1, vl_preds, vl_labels = evaluate()
    current_lr = optimizer.param_groups[0]["lr"]
    scheduler.step()

    history["train_loss"].append(tr_loss)
    history["val_loss"].append(vl_loss)
    history["train_acc"].append(tr_acc)
    history["val_acc"].append(vl_acc)
    history["val_f1"].append(vl_f1)
    history["lr"].append(current_lr)

    marker = " ←" if vl_acc > best_val_acc else ""
    if vl_acc > best_val_acc:
        best_val_acc = vl_acc
        best_preds, best_labels = vl_preds[:], vl_labels[:]
        torch.save({
            "epoch": epoch, "model_state": model.state_dict(),
            "val_acc": vl_acc, "val_f1": vl_f1,
            "classes": class_names, "config": CFG,
        }, ckpt_path)

    print(f"  {epoch:3d}/{CFG['epochs']}   "
          f"{tr_loss:.4f}    {vl_loss:.4f}     "
          f"{vl_acc:.4f}   {vl_f1:.4f}   "
          f"{current_lr:.1e}{marker}")

elapsed = time.time() - t0

print(f"{'─'*55}")
print(f"Done in {elapsed/60:.1f} min  |  best val_acc = {best_val_acc:.4f}")

with open(Path(CFG["output_dir"]) / "history.json", "w") as f:
    json.dump(history, f, indent=2)

epochs_range = range(1, len(history["train_loss"]) + 1)

fig, axes = plt.subplots(1, 3, figsize=(18, 5))
fig.suptitle("Training Curves — PlantVillage CNN", fontsize=15, fontweight="bold")

axes[0].plot(epochs_range, history["train_loss"], label="Train", lw=2)
axes[0].plot(epochs_range, history["val_loss"],   label="Val",   lw=2, ls="--")
axes[0].set_title("Loss"); axes[0].set_xlabel("Epoch")
axes[0].legend(); axes[0].grid(alpha=0.3)

axes[1].plot(epochs_range, history["train_acc"], label="Train", lw=2)
axes[1].plot(epochs_range, history["val_acc"],   label="Val",   lw=2, ls="--")
axes[1].set_title("Accuracy"); axes[1].set_xlabel("Epoch")
axes[1].legend(); axes[1].grid(alpha=0.3)

ax2 = axes[2].twinx()
axes[2].plot(epochs_range, history["val_f1"], label="Val F1",
             lw=2, color="green")
ax2.plot(epochs_range, history["lr"], label="LR",
         lw=1.5, color="purple", ls=":")
axes[2].set_title("Val F1 + LR"); axes[2].set_xlabel("Epoch")
axes[2].set_ylabel("F1"); ax2.set_ylabel("LR")
axes[2].legend(loc="lower left"); ax2.legend(loc="upper right")
axes[2].grid(alpha=0.3)

plt.tight_layout()
plt.savefig(Path(CFG["output_dir"]) / "loss_curves.png", dpi=150)
plt.show()
print("✓ loss_curves.png saved")

report_dict = classification_report(
    best_labels, best_preds,
    target_names=class_names, output_dict=True, zero_division=0
)
per_f1 = {c: report_dict[c]["f1-score"] for c in class_names}
sorted_items = sorted(per_f1.items(), key=lambda x: x[1])
cls_names, cls_scores = zip(*sorted_items)

colors = ["#e74c3c" if s < 0.70 else "#f39c12" if s < 0.85 else "#27ae60"
          for s in cls_scores]

fig, ax = plt.subplots(figsize=(10, 7))
ax.barh(range(len(cls_names)), cls_scores, color=colors, edgecolor="white")
ax.set_yticks(range(len(cls_names)))
ax.set_yticklabels(cls_names, fontsize=9)
ax.set_xlabel("F1 Score")
ax.set_title("Per-Class F1 Score", fontsize=13, fontweight="bold")
ax.axvline(0.70, color="orange", ls="--", alpha=0.6, label="0.70")
ax.axvline(0.85, color="green",  ls="--", alpha=0.6, label="0.85")
ax.set_xlim(0, 1.05); ax.legend(); ax.grid(axis="x", alpha=0.3)
plt.tight_layout()
plt.savefig(Path(CFG["output_dir"]) / "per_class_f1.png", dpi=150)
plt.show()
print("✓ per_class_f1.png saved")

print("\n" + "="*60)
print("CLASSIFICATION REPORT")
print("="*60)
print(classification_report(best_labels, best_preds,
                             target_names=class_names, zero_division=0))

import torch
import torch.nn as nn
import numpy as np
import json, time
from pathlib import Path

from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader, random_split, WeightedRandomSampler
from torch.optim.lr_scheduler import CosineAnnealingLR
from sklearn.metrics import f1_score, classification_report, confusion_matrix
from tqdm.notebook import tqdm
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

data_path = "/content/drive/MyDrive/deeplear final/PlantVillage"

!pip install -q scikit-learn streamlit pyngrok

CFG = {
    "data_path":    "/content/drive/MyDrive/deeplear final/PlantVillage",
    "output_dir":   "/content/drive/MyDrive/deeplear final/outputs/week04",
    "img_size":     224,
    "batch_size":   32,
    "epochs":       3,
    "lr_head":      1e-3,
    "lr_backbone":  1e-4,
    "weight_decay": 1e-4,
    "dropout":      0.4,
    "val_split":    0.2,
    "seed":         42,
    "num_workers":  2,
}

Path(CFG["output_dir"]).mkdir(parents=True, exist_ok=True)
torch.manual_seed(CFG["seed"])
np.random.seed(CFG["seed"])

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}  ({torch.cuda.get_device_name(0)})")

S = CFG["img_size"]

train_transform = transforms.Compose([
    transforms.Resize((S, S)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomVerticalFlip(),
    transforms.RandomRotation(20),
    transforms.ColorJitter(brightness=0.3, contrast=0.3, saturation=0.2),
    transforms.RandomResizedCrop(S, scale=(0.75, 1.0)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
])

val_transform = transforms.Compose([
    transforms.Resize((S, S)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
])

full_dataset = datasets.ImageFolder(root=CFG["data_path"])
class_names  = full_dataset.classes
num_classes  = len(class_names)

n_val   = int(len(full_dataset) * CFG["val_split"])
n_train = len(full_dataset) - n_val
train_idx, val_idx = random_split(
    range(len(full_dataset)), [n_train, n_val],
    generator=torch.Generator().manual_seed(CFG["seed"])
)

class TransformSubset(torch.utils.data.Dataset):
    def __init__(self, dataset, indices, transform):
        self.dataset = dataset; self.indices = indices; self.transform = transform
    def __len__(self): return len(self.indices)
    def __getitem__(self, i):
        from PIL import Image
        img_path, label = self.dataset.imgs[self.indices[i]]
        return self.transform(Image.open(img_path).convert("RGB")), label

train_ds = TransformSubset(full_dataset, train_idx.indices, train_transform)
val_ds   = TransformSubset(full_dataset, val_idx.indices,   val_transform)

train_labels   = [full_dataset.targets[i] for i in train_idx.indices]
class_counts   = np.bincount(train_labels)
sample_weights = 1.0 / class_counts[train_labels]
sampler        = WeightedRandomSampler(sample_weights, len(sample_weights))

train_loader = DataLoader(train_ds, batch_size=CFG["batch_size"],
                          sampler=sampler, num_workers=CFG["num_workers"], pin_memory=True)
val_loader   = DataLoader(val_ds,   batch_size=CFG["batch_size"],
                          shuffle=False, num_workers=CFG["num_workers"], pin_memory=True)

print(f"Train: {len(train_ds)}  Val: {len(val_ds)}  Classes: {num_classes}")

#4. Model: ResNet18
#   Этап 1 (эпохи 1-5):  заморозить backbone, обучать только голову
#   Этап 2 (эпохи 6-15): разморозить backbone, обучать всё с малым lr

def build_resnet18(num_classes, dropout=0.4):
    model = models.resnet18(weights=models.ResNet18_Weights.IMAGENET1K_V1)

    # Замораживаем backbone
    for param in model.parameters():
        param.requires_grad = False

    # Заменяем голову
    in_features = model.fc.in_features  # 512
    model.fc = nn.Sequential(
        nn.Dropout(dropout),
        nn.Linear(in_features, 256),
        nn.ReLU(inplace=True),
        nn.Dropout(dropout * 0.5),
        nn.Linear(256, num_classes),
    )
    return model

model = build_resnet18(num_classes, CFG["dropout"]).to(device)
print(f"ResNet18 loaded  |  trainable params (head only): "
      f"{sum(p.numel() for p in model.parameters() if p.requires_grad):,}")

#5. Training utilities
criterion = nn.CrossEntropyLoss(label_smoothing=0.1)

def get_optimizer(model, stage):
    """stage=1: только голова, stage=2: весь backbone с малым lr"""
    if stage == 1:
        return torch.optim.AdamW(
            filter(lambda p: p.requires_grad, model.parameters()),
            lr=CFG["lr_head"], weight_decay=CFG["weight_decay"]
        )
    else:
        return torch.optim.AdamW([
            {"params": model.fc.parameters(),  "lr": CFG["lr_head"]},
            {"params": [p for n, p in model.named_parameters()
                        if "fc" not in n],      "lr": CFG["lr_backbone"]},
        ], weight_decay=CFG["weight_decay"])

def train_one_epoch(optimizer):
    model.train()
    total_loss, correct, total = 0, 0, 0
    for x, y in tqdm(train_loader, desc="  train", leave=False):
        x, y = x.to(device), y.to(device)
        optimizer.zero_grad(set_to_none=True)
        out  = model(x)
        loss = criterion(out, y)
        loss.backward()
        nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        total_loss += loss.item()
        correct    += (out.argmax(1) == y).sum().item()
        total      += y.size(0)
    return total_loss / len(train_loader), correct / total

@torch.no_grad()
def evaluate():
    model.eval()
    total_loss, correct, total = 0, 0, 0
    all_preds, all_labels = [], []
    for x, y in tqdm(val_loader, desc="  val  ", leave=False):
        x, y = x.to(device), y.to(device)
        out   = model(x)
        loss  = criterion(out, y)
        preds = out.argmax(1)
        total_loss += loss.item()
        correct    += (preds == y).sum().item()
        total      += y.size(0)
        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(y.cpu().numpy())
    acc = correct / total
    f1  = f1_score(all_labels, all_preds, average="weighted", zero_division=0)
    return total_loss / len(val_loader), acc, f1, all_preds, all_labels

#6. Training Loop

STAGE1_EPOCHS = 5
STAGE2_EPOCHS = CFG["epochs"] - STAGE1_EPOCHS

history = {k: [] for k in ["train_loss","val_loss","train_acc","val_acc","val_f1","lr","stage"]}
best_val_acc = 0.0
best_preds, best_labels = [], []
ckpt_path = Path(CFG["output_dir"]) / "resnet18_best.pt"

print(f"\n{'─'*60}")
print(f"  Stage 1: epochs 1-{STAGE1_EPOCHS}  (head only, lr={CFG['lr_head']})")
print(f"  Stage 2: epochs {STAGE1_EPOCHS+1}-{CFG['epochs']}  (full fine-tune, lr={CFG['lr_backbone']})")
print(f"{'─'*60}")

t0 = time.time()
optimizer  = get_optimizer(model, stage=1)
scheduler  = CosineAnnealingLR(optimizer, T_max=CFG["epochs"], eta_min=1e-6)

for epoch in range(1, CFG["epochs"] + 1):

    if epoch == STAGE1_EPOCHS + 1:
        print(f"\n  ── Unfreezing backbone (Stage 2) ──")
        for param in model.parameters():
            param.requires_grad = True
        optimizer = get_optimizer(model, stage=2)
        scheduler = CosineAnnealingLR(optimizer, T_max=STAGE2_EPOCHS, eta_min=1e-6)
        print(f"  Trainable params: {sum(p.numel() for p in model.parameters() if p.requires_grad):,}\n")

    tr_loss, tr_acc = train_one_epoch(optimizer)
    vl_loss, vl_acc, vl_f1, vl_preds, vl_labels = evaluate()
    current_lr = optimizer.param_groups[0]["lr"]
    scheduler.step()

    stage = 1 if epoch <= STAGE1_EPOCHS else 2
    history["train_loss"].append(tr_loss)
    history["val_loss"].append(vl_loss)
    history["train_acc"].append(tr_acc)
    history["val_acc"].append(vl_acc)
    history["val_f1"].append(vl_f1)
    history["lr"].append(current_lr)
    history["stage"].append(stage)

    marker = " ←" if vl_acc > best_val_acc else ""
    if vl_acc > best_val_acc:
        best_val_acc = vl_acc
        best_preds, best_labels = vl_preds[:], vl_labels[:]
        torch.save({"model_state": model.state_dict(), "val_acc": vl_acc,
                    "val_f1": vl_f1, "classes": class_names, "config": CFG}, ckpt_path)

    print(f"  [{stage}] ep{epoch:2d}/{CFG['epochs']}  "
          f"tr={tr_acc:.4f}  vl={vl_acc:.4f}  f1={vl_f1:.4f}  "
          f"lr={current_lr:.1e}{marker}")

elapsed = time.time() - t0
print(f"\nDone in {elapsed/60:.1f} min  |  best val_acc = {best_val_acc:.4f}")

import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0) if torch.cuda.is_available() else "NO GPU")

with open(Path(CFG["output_dir"]) / "resnet18_history.json", "w") as f:
    json.dump(history, f, indent=2)

epochs_range = range(1, len(history["train_acc"]) + 1)
stage_switch = STAGE1_EPOCHS + 0.5

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle("ResNet18 Fine-tuning Curves", fontsize=14, fontweight="bold")

for ax, (tr_key, vl_key, title) in zip(axes, [
    ("train_loss", "val_loss", "Loss"),
    ("train_acc",  "val_acc",  "Accuracy"),
]):
    ax.plot(epochs_range, history[tr_key], label="Train", lw=2)
    ax.plot(epochs_range, history[vl_key], label="Val",   lw=2, ls="--")
    ax.axvline(stage_switch, color="orange", ls=":", lw=1.5, label="Unfreeze backbone")
    ax.set_title(title); ax.set_xlabel("Epoch")
    ax.legend(); ax.grid(alpha=0.3)

plt.tight_layout()
plt.savefig(Path(CFG["output_dir"]) / "resnet18_curves.png", dpi=150)
plt.show()
print("✓ resnet18_curves.png saved")

cm      = confusion_matrix(best_labels, best_preds)
cm_norm = cm.astype(float) / cm.sum(axis=1, keepdims=True).clip(1e-9)

fig, ax = plt.subplots(figsize=(14, 12))
sns.heatmap(cm_norm, annot=True, fmt=".2f",
            xticklabels=class_names, yticklabels=class_names,
            cmap="Greens", ax=ax, linewidths=0.4, annot_kws={"size": 7})
ax.set_title("ResNet18 Confusion Matrix", fontsize=14, fontweight="bold")
ax.set_xlabel("Predicted"); ax.set_ylabel("True")
plt.xticks(rotation=45, ha="right", fontsize=7)
plt.yticks(rotation=0, fontsize=7)
plt.tight_layout()
plt.savefig(Path(CFG["output_dir"]) / "resnet18_confusion.png", dpi=150)
plt.show()

